#!/bin/bash
chinaip_file=/home/whiteip/chinaips
customip_dir=/home/whiteip/custom

# create or update a ipset with iplist file
UPDATE-IPSET() {
	ipset_name=$1
	iplist_file=$2

	if [ -f $iplist_file ] && [ -s $iplist_file ]; then
		echo "update $ipset_name list start ..."
		ipset create -exist $ipset_name hash:net
		ipset flush $ipset_name

		while read ip; do
		  ipset -q add $ipset_name $ip 
		done < $iplist_file

		echo "update $ipset_name list ... done"
	fi
}

# update ips in ipset used by default rules
UPDATE-DEFAULT-IPSET() {
	UPDATE-IPSET "chinaips" $chinaip_file
}

# update ips in ipset used by custom rules
UPDATE-CUSTOM-IPSET() {
	for file in "$customip_dir"/*
	do
		file_name=${file#*$customip_dir/}
		port=${file_name#*--}
		if [[ $port =~ ^-?[0-9]+$ ]]; then
			ipset_name=${file_name%--*}
		else
			ipset_name=$file_name
		fi

		# update custom ipset
		UPDATE-IPSET $ipset_name $file
	done
}

# create iptables CHAIN
CREATE-CHAIN() {
	## create chain BYPASS
	iptables -t nat -N BYPASS
	iptables -t nat -I PREROUTING -p tcp -i $LAN -j BYPASS
}

# add default white list
APPEND-DEFAULT-RULE-WHITELIST() {
	# add local network ips in whitelist 
    iptables -t nat -A BYPASS -p tcp -d 0.0.0.0/8 -j RETURN
    iptables -t nat -A BYPASS -p tcp -d 10.0.0.0/8 -j RETURN
    iptables -t nat -A BYPASS -p tcp -d 127.0.0.0/8 -j RETURN
    iptables -t nat -A BYPASS -p tcp -d 169.254.0.0/16 -j RETURN
    iptables -t nat -A BYPASS -p tcp -d 172.16.0.0/12 -j RETURN
    iptables -t nat -A BYPASS -p tcp -d 192.168.0.0/16 -j RETURN
    iptables -t nat -A BYPASS -p tcp -d 224.0.0.0/4 -j RETURN
    iptables -t nat -A BYPASS -p tcp -d 240.0.0.0/4 -j RETURN
	
	# add china ips in whitelist
 	if [ -f $chinaip_file ] && [ -s $chinaip_file ]; then
		iptables -t nat -A BYPASS -p tcp --match set --match-set chinaips dst -j RETURN
	fi
}

# redirect all other packets to `DEFAULT_PORT`, set by docker environment variable
APPEND-DEFAULT-RULE-REDIRECT() {
        iptables -t nat -A BYPASS -p tcp -j REDIRECT --to $PORT_1
}

# add custom white list in '$customip_dir/myips'
APPEND-CUSTOM-RULE-WHITELIST() {
	for file in "$customip_dir"/*
	do
		file_name=${file#*$customip_dir/}
		port=${file_name#*--}
		[[ $port =~ ^-?[0-9]+$ ]] || ( ipset_name=$file_name && iptables -t nat -A BYPASS -p tcp --match set --match-set $ipset_name dst -j RETURN )
	done
}

# redirect ips in '$customip_dir/myips--1090'
APPEND-CUSTOM-RULE-REDIRECT() {
	for file in "$customip_dir"/*
	do
		file_name=${file#*$customip_dir/}
		port=${file_name#*--}
		if [[ $port =~ ^-?[0-9]+$ ]]; then
			ipset_name=${file_name%--*}
			iptables -t nat -A BYPASS -p tcp --match set --match-set $ipset_name dst -j REDIRECT --to $port
		fi
	done
}

INIT() {
	./clean-rule $LAN
	
	# update ips in ipset
	UPDATE-DEFAULT-IPSET
	UPDATE-CUSTOM-IPSET

	# create new CHAIN
	CREATE-CHAIN

	# append custom whitelist rule
	APPEND-CUSTOM-RULE-WHITELIST
    
    # append dafault whitelist rule
	APPEND-DEFAULT-RULE-WHITELIST

	# append custom redirect rule
	APPEND-CUSTOM-RULE-REDIRECT
	
	# append default redirect rule
	APPEND-DEFAULT-RULE-REDIRECT

	# check all rules
	iptables -t nat -L -vn
}

INIT && bash
